[program:siaps-face-service]
directory=/www/wwwroot/face-siaps
command=/www/wwwroot/face-siaps/.venv/bin/uvicorn app.main:app --host 127.0.0.1 --port 9001
user=www
autostart=true
autorestart=true
startsecs=5
stopsignal=INT
stdout_logfile=/var/log/supervisor/siaps-face-service.log
stderr_logfile=/var/log/supervisor/siaps-face-service-error.log
environment=PYTHONUNBUFFERED="1"
